GET {{host}}{{apiServiceCliente}}/profesor/2/detalleclase/1001
Accept: {{accept}}
Cache-Control: {{cache}}
Content-Type: {{content}}
Authorization: {{token}}

###

GET {{host}}{{apiServiceCliente}}/profesor/2/anotaciones/1001
Accept: {{accept}}
Cache-Control: {{cache}}
Content-Type: {{content}}
Authorization: {{token}}

###
GET {{host}}{{apiServiceCliente}}/profesor/preguntas/2
Accept: {{accept}}
Cache-Control: {{cache}}
Content-Type: {{content}}
Authorization: {{token}}

###
GET {{host}}{{apiServiceCliente}}/profesor/2/alumnos/1001
Accept: {{accept}}
Cache-Control: {{cache}}
Content-Type: {{content}}
Authorization: {{token}}

###
GET {{host}}{{apiService}}/materiasprofesor/2
Accept: {{accept}}
Cache-Control: {{cache}}
Content-Type: {{content}}
Authorization: {{token}}

###
GET {{host}}{{apiService}}/catalogoHorario/profesor/2/fecha/20200827
Accept: {{accept}}
Cache-Control: {{cache}}
Content-Type: {{content}}
Authorization: {{token}}

###
